project:
  type: website
  lib-dir: libs
  output-dir: docs
  

website:
  title: "Centre for Applied Bioinformatics R Workshop"
  google-analytics: 
    tracking-id: "G-T6VR3PMQ4R"
    anonymize-ip: true
  sidebar:
    style: floating
    tools:
      - icon: twitter
        href: https://twitter.com/bradyajohnston
      - icon: github
        href: https://github.com/BradyAJohnston/2022-07-04-R-workshop/
    search: true
    contents:
      - section: "Workshop Details"
        contents:
        - index.Rmd
        - before-we-start.Rmd
        - about.qmd
        - text: Code Cheat Sheet
          href: https://hackmd.io/-YLX9fHvQyK1Qj5GCMUUIw?view
        - text: Code Q & A
          href: https://hackmd.io/NAwVU2RUQWKNkC-ZzY-7RQ?view
        - text: Code Handout
          href: code-handout.R
        - text: Carpentries Code of Conduct
          href: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html
      - section: "Download Data"
        contents:
        - text: Data Surveys 
          href: data_raw/surveys.csv
        - text: Data TL Database
          href: TL_database.xlsx
        - text: Data Cell
          href: data_raw/example_cell_data.xslx
      - section: "Starting with R"
        contents:
        - 01-intro-to-r.Rmd
        - 02-starting-with-data.Rmd
        - 03-dplyr.Rmd
      - section: "Visualisation"
        contents:
        - 04-visualization-ggplot2.Rmd
        - 05_ggplot2_extensions.qmd
      - section: "Reproducible Reporting"
        contents:
        - rmarkdown.qmd
        - scratch.Rmd
      # - 05-r-and-databases.Rmd
      - section: "Stats in R"
        contents:
        - stats.qmd
      - section: "Useful Links"
        contents:
        - links.qmd
execute: 
  freeze: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-link: true



