project:
  type: website
  lib-dir: libs
  output-dir: docs
  

website:
  title: "CAB R Workshop"
  sidebar:
    style: floating
    tools:
      - icon: twitter
        href: https://twitter.com/bradyajohnston
      - icon: github
        href: https://github.com/BradyAJohnston/2022-07-04-R-workshop/
    search: true
    contents:
      - section: "Home"
        contents:
        - index.Rmd
        - CONDUCT.Rmd
      - section: "Introduction"
        contents:
        - about.qmd
        - before-we-start.Rmd
      - section: "Starting with R"
        contents:
        - 01-intro-to-r.Rmd
        - 02-starting-with-data.Rmd
        - 03-dplyr.Rmd
      - section: "Visualisation"
        contents:
        - 04-visualization-ggplot2.Rmd
      # - 05-r-and-databases.Rmd
execute: 
  freeze: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true



